[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "d2f"
version = "0.0.1"
dependencies = ["setuptools", "wheel"]

[project.scripts]
d2f = "main:main"
